export const CUSTOMER_TYPES = ['REGULAR', 'PREMIUM', 'VIP'];
export const INTERACTION_TYPES = ['PURCHASE', 'INQUIRY', 'COMPLAINT', 'RETURN'];
export const INTERACTION_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
